# -- 코드를 입력하세요
# SELECT DATE_FORMAT(onl.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, onl.PRODUCT_ID	, onl.USER_ID, onl.SALES_AMOUNT
# from ONLINE_SALE onl
# where DATE_FORMAT(onl.SALES_DATE, "%Y-%m")  = "2022-03"
# union
# SELECT   DATE_FORMAT(offl.SALES_DATE, ", %Y-%m-%d") as SALES_DATE, offl.PRODUCT_ID	, NULL, offl.SALES_AMOUNT
# from OFFLINE_SALE offl
# where DATE_FORMAT(offl.SALES_DATE, ", %Y-%m")  = "2022-03"
# ORDER BY SALES_DATE ,PRODUCT_ID, USER_ID

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID