SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d
WHERE EXISTS(SELECT *
             FROM SKILLCODES s
             WHERE s.NAME IN ('Python', 'C#') AND
             d.SKILL_CODE & s.CODE = s.CODE )
ORDER BY ID
# SELECT 1
# FROM DEVELOPERS s
# WHERE  s.SKILL_CODE & b'100000000' = b'100000000'